import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Renders a plain-text roster suitable for printing.
// A full PDF renderer (e.g. pdf-lib) can replace this body in Phase 2.
function renderRoster(list: any): string {
  const lines: string[] = [
    `DEATH FIELDS ARENA — ARMY ROSTER`,
    ``,
    `${list.name}`,
    `Faction: ${list.faction?.name ?? 'Unknown'}`,
    `Points:  ${list.points_total} / 1000`,
    ``,
    `${'─'.repeat(60)}`,
  ];

  for (const entry of list.army_entries ?? []) {
    const u = entry.unit_type;
    lines.push('');
    lines.push(`${u.name}  ×${entry.quantity}  (${u.points * entry.quantity}pts)`);
    lines.push(`  Role: ${u.role}  |  Act:${u.actions} Mov:${u.movement}" Mel:${u.melee_attack}+ Ran:${u.ranged_attack}+ Def:${u.defence}+ HP:${u.health}`);
    for (const ability of u.abilities ?? []) {
      lines.push(`  ★ ${ability.name} — ${ability.description}`);
    }
    for (const weapon of u.weapons ?? []) {
      const kw = (weapon.weapon_keywords ?? [])
        .map((wk: any) => wk.parameter ? `${wk.keyword.name}(${wk.parameter})` : wk.keyword.name)
        .join(', ');
      lines.push(`  ⚔ ${weapon.name}  ${weapon.range_inches ?? '—'}  A${weapon.num_attacks}  D${weapon.damage}  AP${weapon.defence_mod}${kw ? `  [${kw}]` : ''}`);
    }
  }

  lines.push('');
  lines.push(`${'─'.repeat(60)}`);
  lines.push(`Generated by Death Fields Arena Army Builder`);
  lines.push(`${list.faction?.store_url ?? ''}`);

  return lines.join('\n');
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const { listId } = await req.json();
  if (!listId) {
    return new Response(JSON.stringify({ error: 'Missing listId' }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  // Verify caller owns the list (or it's public)
  const authHeader = req.headers.get('Authorization') ?? '';
  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_ANON_KEY')!,
    { global: { headers: { Authorization: authHeader } } },
  );

  const { data, error } = await supabase
    .from('army_lists')
    .select(`
      *,
      faction: factions (*),
      army_entries (
        id, quantity,
        unit_type: unit_types (
          *,
          unit_weapons ( weapon: weapons ( *, weapon_keywords ( keyword: keywords (*), parameter ) ) )
        )
      )
    `)
    .eq('id', listId)
    .single();

  if (error || !data) {
    return new Response(JSON.stringify({ error: 'List not found or access denied' }), {
      status: 404,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const payload = {
    ...data,
    army_entries: (data.army_entries ?? []).map((e: any) => ({
      ...e,
      unit_type: {
        ...e.unit_type,
        weapons: e.unit_type?.unit_weapons?.map((uw: any) => uw.weapon) ?? [],
        unit_weapons: undefined,
      },
    })),
  };

  const text = renderRoster(payload);

  return new Response(text, {
    status: 200,
    headers: {
      ...corsHeaders,
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="${data.name.replace(/[^a-z0-9]/gi, '_')}_roster.txt"`,
    },
  });
});
