insert into public.keywords (name, description) values
  ('Blast (X)',           'Causes 1 additional point of Damage for each successful hit to all Models within X\" of the original Target. Models wounded are Knocked Back directly away from the original target.'),
  ('Cavalry',            'Model may not move vertically under any circumstances unless via ramps or stairs. May not Climb or use Ladders, but may Jump.'),
  ('Charged (X)',        'Model or weapon may make a Charged Shot Action (2). Increases damage of each successful hit by X. Attacking model receives 1 Stress after.'),
  ('Crit Damage',        'Attacker gains an extra point of Damage for every natural roll of a 0.'),
  ('Crit Modifier',      'Attacker gains an additional -1 Armour Penetration for every natural roll of a 0.'),
  ('Crit Stress',        'Defender immediately receives 1 Stress for every natural roll of a 0 in the Attacker''s Attack roll.'),
  ('Crit AP',            'Attacker gains an additional -1 Armour Penetration for every natural roll of a 0.'),
  ('Ignores Cover',      'Attack prevents the Defender from gaining any benefit of Cover or Defensive Positions.'),
  ('Ignores Intervening','Attack ignores the negative modifier from Intervening Terrain.'),
  ('Immobile',           'Model may not make Move Actions under any circumstances and is never Knocked Back.'),
  ('Knock Back',         'Models targeted are Knocked Back an additional 1\" for each damage caused.'),
  ('Large Target',       'All Ranged Attacks targeting this model gain +1 to Attack rolls and gain Ignores Intervening.'),
  ('Mobile',             'Weapon ignores the negative modifier to Ranged Attack rolls for having performed a Move action prior to the Ranged Attack Action during the same Activation.'),
  ('Order',              'Model may issue an Order to another Model within 6\", transferring one available Action. Only models with the Order keyword may use this. Receiving model must not have an Activation Token.'),
  ('Shield Breaker',     'Prevents the Defender from making any Shield Saves against this Attack.'),
  ('Shock',              'Defender immediately receives 1 Stress for each successful hit in the Ranged or Melee Attack roll.'),
  ('Slow',               'Ranged Weapons with this keyword may only make one Ranged Attack Action per Activation.'),
  ('Split Fire (X)',     'Model may choose multiple targets within X\" of one another. Split total Attacks between targets. Resolve sequence separately for each target.'),
  ('Steadfast',          'Model is not Knocked Back at the end of Ranged or Melee Attack Sequences.'),
  ('Template',           'Does not measure range. Place template with small end touching Attacker''s base. Models at least partially under template are hit. Models hit may not make Fire Back Reaction.'),
  ('Weapons Platform',   'All Actions become Action (2). Model cannot use the Interact Action.'),
  ('One Use',            'This weapon may only be used once per game.')
on conflict (name) do nothing;
