-- abilities stored as JSONB; \" escapes double-quotes inside JSON strings
with fac as (select id, slug from public.factions)
insert into public.unit_types
  (faction_id, name, role, actions, movement, melee_attack, ranged_attack, defence, health, points, max_per_army, abilities, base_size_mm, sort_order)
select fac.id,
       v.uname,
       v.role::unit_role,
       v.acts, v.mov, v.mel, v.ran, v.def, v.hp,
       v.pts,
       v.max_pa,
       v.ab::jsonb,
       25,
       v.sord
from (values
  -- ── BULLDOGS ────────────────────────────────────────────────────────────────
  ('bulldogs','The Red Devil','captain',3,7,5,5,4,5,124,1,
   '[{"name":"Command","description":"This Model has the Order Keyword."},{"name":"Inspiring Presence","description":"When this Model Activates, other Friendly Models within 6\" may remove 1 Stress."},{"name":"Killer''s Instinct","description":"This Model may re-roll any of its Melee Attack rolls."},{"name":"Who Dares Wins","description":"Models in this team ignore the Stress Modifier to their Movement stat."}]',
   1),
  ('bulldogs','Master of The Line','captain',3,7,5,5,4,5,103,1,
   '[{"name":"Command","description":"This Model has the Order Keyword."},{"name":"On My Mark!","description":"Friendly Models within 4\" may re-roll one Ranged Attack die per Action."},{"name":"Old Hand","description":"This Model counts as having 1 less Stress."},{"name":"Volley Fire!","description":"Models in this team gain +1 Attack during Ranged Attacks when within 2\" of a Friendly Model. Additionally Models in this team do not receive Stress from making a Fire Back Reaction."}]',
   2),
  ('bulldogs','The Old Sweat','captain',3,7,5,5,4,5,115,1,
   '[{"name":"Command","description":"This Model has the Order Keyword."},{"name":"Veteran","description":"This Model may re-roll one die in their Attack rolls and Defence rolls."},{"name":"Keep Moving!","description":"Friendly Models that Activate within 4\" of this Model may add 2\" to their Movement."},{"name":"Stiff Upper Lip","description":"At the start of their Activation, Models in this team may remove 1 Stress. When a Model in this Team makes a Recover Action they roll 2 d5 and select the highest result."}]',
   3),
  ('bulldogs','L.M.G. Gunner','specialist',2,7,5,5,4,5,95,2,
   '[{"name":"Saturated Fire","description":"May re-roll any Ranged Attack die. If you choose to re-roll any dice, at the end of the Action this model receives 1 Stress."}]',
   4),
  ('bulldogs','Grenadier','specialist',2,7,5,5,4,5,96,2,
   '[{"name":"Buckshee Ammo","description":"May re-roll one failed Ranged Attack Dice per Ranged Attack."}]',
   5),
  ('bulldogs','Electro Gunner','specialist',2,7,5,5,4,5,93,2,
   '[]',
   6),
  ('bulldogs','Whistler','specialist',2,7,5,5,4,5,105,2,
   '[{"name":"On the Boil","description":"This Model may ignore the Slow Keyword. If this Model performs two Ranged Attack Actions it gains +1 Stress."}]',
   7),
  ('bulldogs','Commando','core',2,7,5,5,4,5,95,NULL,
   '[{"name":"Cool in Cover","description":"This Model gains +1 to their Ranged Attack rolls when in Cover."}]',
   8),
  ('bulldogs','Rifleman','core',2,7,5,5,4,5,93,NULL,
   '[{"name":"In the Line","description":"This Model ignores the Stress Modifier to Ranged Attack rolls when within 2\" of another Friendly Model."}]',
   9),
  ('bulldogs','Tommy','core',2,7,5,5,4,5,94,NULL,
   '[{"name":"Pepper Potting","description":"When this Model performs a Ranged Attack Action they may make a free 2\" Move at the end of the Action. Must follow all of the usual rules for Move Actions."}]',
   10),
  ('bulldogs','Brew Sgt.','core',2,7,5,5,4,5,95,2,
   '[{"name":"Built on Tea","description":"Friendly Models that Activate within 4\" of this Model may remove 1 Stress at the start of their Activation."},{"name":"Cuppa?","description":"Action: Any Friendly Model in base contact with this Model, including this Model, may perform this Action. Remove all Stress from this Model."}]',
   11),
  ('bulldogs','Combat Medic','core',3,7,5,5,4,5,95,2,
   '[{"name":"Medic!","description":"Action: This model or a model in base contact may heal d5 wounds."}]',
   12),

  -- ── LES GROGNARDS ───────────────────────────────────────────────────────────
  ('les-grognards','Commandant de Ligne','captain',3,6,4,4,4,5,119,1,
   '[{"name":"Command","description":"This Model has the Order Keyword."},{"name":"Alert","description":"May make Reactions whilst it has the Activated token."},{"name":"Kinetic Shield","description":"8+ Shield Save against Ranged Attacks only."},{"name":"Les Troupes de Ligne","description":"Whenever a model in this team makes a successful Ranged Attack action other friendly models within 4\" and LoS may remove 1 stress."}]',
   1),
  ('les-grognards','Garde de Kinetic','specialist',2,7,5,4,5,5,98,2,
   '[{"name":"Overload!","description":"May re-roll any Ranged Attack die. If you choose to re-roll any dice, at the end of the Action this model receives 1 Stress."}]',
   2),
  ('les-grognards','Garde de Grenade','specialist',2,7,5,4,5,5,113,2,
   '[{"name":"Feu de Pluie!","description":"This Model may ignore the Slow Keyword. If this Model performs two Ranged Attack Actions it gains +1 Stress."}]',
   3),
  ('les-grognards','Garde de Fusioner','specialist',2,7,5,4,5,5,95,2,
   '[{"name":"Overload!","description":"May re-roll any Ranged Attack die. If you choose to re-roll any dice, at the end of the Action this model receives 1 Stress."}]',
   4),
  ('les-grognards','Garde de Flame','specialist',2,7,5,4,5,5,104,2,
   '[{"name":"Mur de feu!","description":"This Model may ignore the Slow Keyword. If this Model performs two Ranged Attack Actions it gains +1 Stress."}]',
   5),
  ('les-grognards','Garde d''Assaut','core',2,7,4,4,5,5,106,NULL,
   '[{"name":"Deadly Precision","description":"This model gains Crit Damage on all Melee Attacks."}]',
   6),
  ('les-grognards','Officier de Coordination','core',2,7,5,4,5,5,97,2,
   '[{"name":"Comms","description":"A Model with the Order Keyword may issue an order to models within 6\" of this model following all of the rules for issuing orders."},{"name":"Volley Fire","description":"All Friendly Models within 4\" and LoS of this Model may re-roll one Ranged Attack die per Ranged Attack Action."}]',
   7),
  ('les-grognards','Infirmier de Combat','core',3,7,5,4,5,5,97,2,
   '[{"name":"Medic!","description":"Action: The bearer or a model in base contact may heal d5 wounds."},{"name":"Through Grit Alone!","description":"Action: Friendly models within 6\" may remove 1 Stress."}]',
   8),
  ('les-grognards','Sergent de Ligne','core',2,7,5,4,5,5,93,2,
   '[{"name":"Inspiring Presence","description":"Friendly Models that activate within 6\" of this Model may remove 1 Stress at the start of their Activation."},{"name":"Push on!","description":"Friendly Models that Activate within 4\" of this Model may add 2\" to their Movement."}]',
   9),
  ('les-grognards','Marqueur de Mort','core',2,7,5,3,5,5,92,NULL,
   '[{"name":"Sharpshooter","description":"Ignores Intervening Terrain when making a Ranged Attack."},{"name":"Precision Shot","description":"This model''s ranged attacks gain the Keyword Crit AP."}]',
   10),
  ('les-grognards','Vétéran de Ligne','core',2,6,5,4,5,5,93,4,
   '[{"name":"Kinetic Shield","description":"8+ Shield Roll against Ranged attacks."},{"name":"Veteran","description":"Roll a d10. On 6+ this model may make an additional Action once per Activation."}]',
   11),
  ('les-grognards','Voltigeur','core',2,8,5,4,5,5,93,NULL,
   '[{"name":"Skirmisher","description":"This Model ignores the effects of Difficult Ground and receives an additional +1 to Defence Rolls when in Cover."}]',
   12),

  -- ── EINHERJAR ───────────────────────────────────────────────────────────────
  ('einherjar','Konungr','captain',3,6,4,5,4,5,106,1,
   '[{"name":"Hearth-Call","description":"This Model has the Order Keyword."},{"name":"Svalinn Shield","description":"This model gains a 8+ shield save and adds +1 extra dice to their Defence rolls in Melee and Ranged combat."},{"name":"Slayer''s Instinct","description":"This Model may re-roll any of its Melee Attack rolls."},{"name":"Shield Wall!","description":"Models in this Team receive +1 to Defence Rolls when within 2\" of another Friendly Model."}]',
   1),
  ('einherjar','Jarl','captain',2,6,4,5,4,5,101,2,
   '[{"name":"Hearth-Call","description":"This Model has the Order Keyword."},{"name":"Svalinn Shield","description":"This model gains a 8+ shield save and adds +1 dice to their defence rolls in melee and ranged combat."},{"name":"Raid!","description":"Friendly Models that Activate within 4\" of this Model may add 2\" to their Movement."}]',
   2),
  ('einherjar','Berserker','specialist',2,6,4,5,4,5,104,1,
   '[{"name":"Slayer''s Instinct","description":"This Model may re-roll any of its Melee Attack rolls."}]',
   3),
  ('einherjar','Muspel-Warder','specialist',2,6,4,5,4,5,107,2,
   '[{"name":"Fury of Muspelheim","description":"When rolling for damage, roll 2 d5 and choose the highest result."}]',
   4),
  ('einherjar','Thunder Caller','specialist',2,6,4,5,4,5,101,2,
   '[]',
   5),
  ('einherjar','Sky-Shatterer','specialist',2,6,4,5,4,5,99,2,
   '[]',
   6),
  ('einherjar','Skald','core',2,6,4,5,4,5,94,2,
   '[{"name":"Skald-Song","description":"Friendly Models that Activate within 6\" of this Model may remove 1 Stress at the start of their Activation."},{"name":"Echoes of Valhalla","description":"When this Model Activates, Friendly models within 6\" may remove 1 Stress."}]',
   7),
  ('einherjar','Foringjar','core',2,6,4,5,4,5,99,NULL,
   '[{"name":"Stalwart","description":"This Model is not Knocked Back as the result of a Ranged Attack."}]',
   8),
  ('einherjar','Hird','core',2,6,4,5,4,5,89,NULL,
   '[{"name":"Steady-Hand","description":"May re-roll one failed Ranged Attack Dice per Ranged Attack."}]',
   9),
  ('einherjar','Bondsman','core',2,6,4,5,4,5,86,NULL,
   '[]',
   10),

  -- ── OOH RAH ─────────────────────────────────────────────────────────────────
  ('ooh-rah','Lieutenant','captain',3,7,5,5,4,5,108,1,
   '[{"name":"Command","description":"This Model has the Order Keyword."},{"name":"Semper-Fi!","description":"When this Model Activates, Friendly models within 6\" may remove 1 Stress."},{"name":"Target Overlay","description":"Friendly Models within 6\" ignore Intervening Terrain modifier during Ranged Attack Actions."},{"name":"Leathernecks","description":"Models in this team may re-roll one die per Defence Roll."}]',
   1),
  ('ooh-rah','Staff Sergeant','captain',3,7,5,5,5,5,108,1,
   '[{"name":"Command","description":"This Model has the Order Keyword."},{"name":"Inspiring Presence","description":"Models that activate within 6\" of this model may remove 1 stress at the start of their Activation."},{"name":"Tactical Advisor","description":"Friendly Models within 4\" may re-roll one Ranged Attack die per Action."}]',
   2),
  ('ooh-rah','Sergeant','captain',3,7,5,5,5,5,99,1,
   '[{"name":"Command","description":"This Model has the Order Keyword."},{"name":"Ooh Rah!","description":"Action: Friendly Models within 6\" may remove d5 Stress."}]',
   3),
  ('ooh-rah','Auto Laser Rifleman','specialist',2,7,5,5,5,5,99,2,
   '[{"name":"Overload!","description":"May re-roll any Ranged Attack die. If you choose to re-roll any dice, at the end of the Action this model receives 1 Stress."}]',
   4),
  ('ooh-rah','Flamer Rifleman','specialist',2,7,5,5,5,5,98,2,
   '[{"name":"Burn ''em Out!","description":"This Model may ignore the Flamer Slow Keyword. If this Model performs two Ranged Attack Actions it gains +1 Stress."}]',
   5),
  ('ooh-rah','Sniper','specialist',2,7,5,3,5,5,110,2,
   '[{"name":"Digital Optics","description":"This Model may re-roll one Failed Ranged Attack die."},{"name":"Concealed Position","description":"This Model receives an additional +1 to Defence Rolls when benefiting from Cover."}]',
   6),
  ('ooh-rah','Breacher','core',2,7,5,5,5,5,98,2,
   '[]',
   7),
  ('ooh-rah','Combat Medic','core',3,7,5,5,5,5,100,1,
   '[{"name":"Medic!","description":"Action: The bearer or a model in base contact may heal d5 wounds."},{"name":"Field Surgeon","description":"Friendly Models within 4\" of this Model gain an additional 8+ Save against all Damage."}]',
   8),
  ('ooh-rah','Fire Team Leader','core',2,7,5,5,5,5,94,NULL,
   '[{"name":"Command","description":"This Model has the Order Keyword."},{"name":"Fire Coordinator","description":"Friendly Models within 4\" of this Model gain +1 to Ranged Attack rolls."},{"name":"Fire Team Leader (x)","description":"May include 1 Fire Team Leader in Team for every 2 Rifleman."}]',
   9),
  ('ooh-rah','Rifleman','core',2,7,5,5,5,5,89,NULL,
   '[{"name":"It''s What We Do","description":"May re-roll one Ranged Attack Dice."}]',
   10),

  -- ── RAUMJÄGER ───────────────────────────────────────────────────────────────
  ('raumjager','Einsatzkommandant','captain',3,7,5,4,6,5,104,1,
   '[{"name":"Befehlshaber","description":"This Model has the Order Keyword."},{"name":"Kinetic Shield","description":"8+ Shield Save against Ranged Attacks only."},{"name":"Vorrücken!","description":"Friendly Models that Activate within 6\" of this Model may add 2\" to their Movement."},{"name":"Reaktionskraft","description":"All Models in this Team are considered to be 3\" further away when selected as the Target of a Ranged Attack."}]',
   1),
  ('raumjager','Flammenjäger','specialist',2,7,5,4,6,5,102,4,
   '[{"name":"Kinetic Shield","description":"8+ Shield Save against Ranged Attacks only."},{"name":"Überlastung!","description":"This Model may ignore the Flamer Slow Keyword. If this Model performs two Ranged Attack Actions it gains +1 Stress."}]',
   2),
  ('raumjager','Totenjäger','specialist',2,7,5,4,6,5,97,4,
   '[{"name":"Kinetic Shield","description":"8+ Shield Save against Ranged Attacks only."},{"name":"Gravatic Stabilisers","description":"This model''s Ranged Attacks gain the Mobile Keyword."}]',
   3),
  ('raumjager','Plasmajäger','specialist',2,7,5,4,6,5,99,4,
   '[{"name":"Kinetic Shield","description":"8+ Shield Save against Ranged Attacks only."},{"name":"Thermal Optics","description":"Ignores Intervening Terrain."}]',
   4),
  ('raumjager','Kampfsanitäter','core',3,7,5,5,6,5,100,1,
   '[{"name":"Kinetic Shield","description":"8+ Shield Save against Ranged Attacks only."},{"name":"Medic!","description":"Action: This model or a model in base contact may heal d5 wounds."},{"name":"Inspiring Presence","description":"Friendly Models that activate within 6\" of this Model may remove 1 Stress at the start of their Activation."}]',
   5),
  ('raumjager','Erfahrener Jäger','core',2,7,5,4,6,5,98,NULL,
   '[{"name":"Kinetic Shield","description":"8+ Shield Save against Ranged Attacks only."},{"name":"Spurfinder","description":"This Model has the Order Keyword."},{"name":"Tactical Advisor","description":"Friendly Models within 4\" may re-roll one Ranged Attack die per Action."}]',
   6),
  ('raumjager','Eiserne Jäger','core',2,7,5,4,6,5,97,NULL,
   '[{"name":"Kinetic Shield","description":"8+ Shield Save against Ranged Attacks only."},{"name":"Ausrücken","description":"When this model performs the Disengage (2) Action it may perform 1 additional Action this Activation."},{"name":"Eiserne Will","description":"At the beginning of this Model''s activation you may remove 1 Stress from this Model."}]',
   7),

  -- ── SNEAKFEET ───────────────────────────────────────────────────────────────
  ('sneakfeet','Quiet-flinger','captain',3,6,7,3,6,5,116,1,
   '[{"name":"Shirif","description":"This Model has the Order Keyword."},{"name":"Marksman","description":"This model ignores the -1 modifier when not targeting the closest enemy model with a Ranged Attack."},{"name":"Unseen Marksmen","description":"All Models in this Team gain a +1 to Defence Rolls when selected as the target of a Ranged Attack from over 12\" away."}]',
   1),
  ('sneakfeet','Hardfoot','captain',3,6,6,5,6,5,105,1,
   '[{"name":"Shirif","description":"This Model has the Order Keyword."},{"name":"Slippery","description":"8+ Shield Save against Ranged and Melee Attacks only."},{"name":"Slight of Stature","description":"Attacks that target models in this Team always suffer an additional -1 modifier to their Attack Rolls."}]',
   2),
  ('sneakfeet','Grass-whistler','specialist',2,6,7,3,6,5,108,4,
   '[{"name":"Marksman","description":"This model ignores the -1 modifier when not targeting the closest enemy model with a Ranged Attack."},{"name":"Concealed Position","description":"This Model receives an additional +1 to Defence Rolls when benefiting from Cover."}]',
   3),
  ('sneakfeet','Bombarder','core',2,6,7,5,6,5,102,4,
   '[{"name":"Bag o'' Bombs!","description":"This Model may re-roll its Ranged Attack Dice when making a Ranged Attack with Frag Grenades."},{"name":"Slippery","description":"8+ Shield Save against Ranged and Melee Attacks only."}]',
   4),
  ('sneakfeet','Pointfoot','core',2,6,7,5,6,5,88,2,
   '[{"name":"Binoculars","description":"All Friendly Models within 4\" of this model gain +1 to their ranged attack rolls."},{"name":"Comms","description":"A Captain may issue an order to models within 6\" of this model following all of the rules for issuing orders."},{"name":"Concealed Position","description":"This Model receives an additional +1 to Defence Rolls when benefiting from Cover."}]',
   5),
  ('sneakfeet','Cook','core',2,6,5,5,5,5,106,2,
   '[{"name":"A Hearty Meal","description":"Friendly Models that activate within 6\" of this model may remove 1 stress at the start of their Activation."},{"name":"Second Breakfast","description":"Friendly Models that activate within 4\" of this model may remove 1 Damage at the start of their Activation."},{"name":"Slippery","description":"8+ Shield Save against Ranged and Melee Attacks only."}]',
   6),
  ('sneakfeet','Quickfoot','core',2,7,5,5,6,5,95,NULL,
   '[{"name":"Light Footed","description":"This Model ignores the effects of Difficult Ground."},{"name":"Fast Hands","description":"This Model may re-roll one failed Attack roll per Attack Action."},{"name":"Slippery","description":"8+ Shield Save against Ranged and Melee Attacks only."}]',
   7),
  ('sneakfeet','Youngfoot','core',2,6,7,5,6,5,85,NULL,
   '[{"name":"Beginner''s Luck","description":"When this model receives damage roll a d10 and call \"odds\" or \"evens\". If correct, reduce the damage received to 1."},{"name":"Enthusiastic","description":"This Model may re-roll any of their Ranged Attack dice."}]',
   8),
  ('sneakfeet','Stoutfoot','core',2,6,7,5,5,5,91,NULL,
   '[{"name":"Stubborn","description":"At the beginning of this Model''s activation you may remove 1 Stress from this Model."},{"name":"Slippery","description":"8+ Shield Save against Ranged and Melee Attacks only."}]',
   9)

) as v(fac_slug, uname, role, acts, mov, mel, ran, def, hp, pts, max_pa, ab, sord)
join fac on fac.slug = v.fac_slug
on conflict (faction_id, name) do nothing;
