-- faction_slug included in every row to disambiguate units with the same name
-- (e.g. "Rifleman" and "Combat Medic" exist in multiple factions)
with
  ut as (
    select ut.id, ut.name, f.slug as faction_slug
    from public.unit_types ut
    join public.factions f on f.id = ut.faction_id
  ),
  w as (select id, name from public.weapons)
insert into public.unit_weapons (unit_type_id, weapon_id)
select ut.id, w.id
from (values
  -- bulldogs
  ('bulldogs','The Red Devil',       'Revolver'),
  ('bulldogs','The Red Devil',       'Energy Sabre'),
  ('bulldogs','Master of The Line',  'Bulldog Rifle'),
  ('bulldogs','Master of The Line',  'Bayonet'),
  ('bulldogs','The Old Sweat',       'SMG'),
  ('bulldogs','The Old Sweat',       'Bionic Arm'),
  ('bulldogs','L.M.G. Gunner',       'L.M.G.'),
  ('bulldogs','L.M.G. Gunner',       'Fists'),
  ('bulldogs','Grenadier',           'Bulldogs Grenade Launcher'),
  ('bulldogs','Grenadier',           'Fists'),
  ('bulldogs','Electro Gunner',      'Electrocannon'),
  ('bulldogs','Electro Gunner',      'Fists'),
  ('bulldogs','Whistler',            'The Whistler'),
  ('bulldogs','Whistler',            'Fists'),
  ('bulldogs','Commando',            'Bulldog Rifle'),
  ('bulldogs','Commando',            'Boot Knife'),
  ('bulldogs','Rifleman',            'Bulldog Rifle'),
  ('bulldogs','Rifleman',            'Bayonet'),
  ('bulldogs','Tommy',               'Bulldog Rifle'),
  ('bulldogs','Tommy',               'Bayonet'),
  ('bulldogs','Brew Sgt.',           'Bulldog Rifle'),
  ('bulldogs','Brew Sgt.',           'Fists'),
  ('bulldogs','Combat Medic',        'SMG'),
  ('bulldogs','Combat Medic',        'Fists'),
  -- les grognards
  ('les-grognards','Commandant de Ligne',      'Chain Sabre'),
  ('les-grognards','Commandant de Ligne',      'Energy Pistol'),
  ('les-grognards','Garde de Kinetic',         'Kinetic Cannon'),
  ('les-grognards','Garde de Kinetic',         'Fists'),
  ('les-grognards','Garde de Grenade',         'Les Grognards Grenade Launcher'),
  ('les-grognards','Garde de Grenade',         'Fists'),
  ('les-grognards','Garde de Fusioner',        'Fusion Gun'),
  ('les-grognards','Garde de Fusioner',        'Fists'),
  ('les-grognards','Garde de Flame',           'Les Grognards Flamer'),
  ('les-grognards','Garde de Flame',           'Fists'),
  ('les-grognards','Garde d''Assaut',          'Chain Sabre'),
  ('les-grognards','Garde d''Assaut',          'Energy Pistol'),
  ('les-grognards','Garde d''Assaut',          'Les Grognards Frag Grenade'),
  ('les-grognards','Officier de Coordination', 'Grognard Rifle'),
  ('les-grognards','Officier de Coordination', 'Bayonet'),
  ('les-grognards','Infirmier de Combat',      'Grognard Rifle'),
  ('les-grognards','Infirmier de Combat',      'Bayonet'),
  ('les-grognards','Sergent de Ligne',         'Grognard Rifle'),
  ('les-grognards','Sergent de Ligne',         'Bayonet'),
  ('les-grognards','Marqueur de Mort',         'Grognard Rifle'),
  ('les-grognards','Marqueur de Mort',         'Bayonet'),
  ('les-grognards','Vétéran de Ligne',         'Grognard Rifle'),
  ('les-grognards','Vétéran de Ligne',         'Bayonet'),
  ('les-grognards','Voltigeur',                'Grognard Rifle'),
  ('les-grognards','Voltigeur',                'Bayonet'),
  -- einherjar
  ('einherjar','Konungr',        'Blood Axe'),
  ('einherjar','Jarl',           'Blood Axe'),
  ('einherjar','Berserker',      'Dual Blood Axe'),
  ('einherjar','Muspel-Warder',  'Heavy Flamer'),
  ('einherjar','Muspel-Warder',  'Fists'),
  ('einherjar','Thunder Caller', 'Thunder Cannon'),
  ('einherjar','Sky-Shatterer',  'Einherjar Grenade Launcher'),
  ('einherjar','Sky-Shatterer',  'Fists'),
  ('einherjar','Skald',          'M.A.R.'),
  ('einherjar','Skald',          'Fists'),
  ('einherjar','Foringjar',      'M.A.R.'),
  ('einherjar','Foringjar',      'Knife'),
  ('einherjar','Hird',           'Shotgun'),
  ('einherjar','Hird',           'Fists'),
  ('einherjar','Bondsman',       'M.A.R.'),
  ('einherjar','Bondsman',       'Fists'),
  -- ooh rah
  ('ooh-rah','Lieutenant',          'Hi-Vol. Pistol'),
  ('ooh-rah','Lieutenant',          'Fists'),
  ('ooh-rah','Staff Sergeant',      'Hi-Vol. SMG'),
  ('ooh-rah','Staff Sergeant',      'Fists'),
  ('ooh-rah','Sergeant',            'Hi-Vol. Carbine'),
  ('ooh-rah','Sergeant',            'Hi-Vol. Carbine (Auto)'),
  ('ooh-rah','Sergeant',            'Fists'),
  ('ooh-rah','Auto Laser Rifleman', 'Hi-Vol. Auto Gun'),
  ('ooh-rah','Auto Laser Rifleman', 'Fists'),
  ('ooh-rah','Flamer Rifleman',     'Ooh Rah Flamer'),
  ('ooh-rah','Flamer Rifleman',     'Fists'),
  ('ooh-rah','Sniper',              'Hi-Vol. Sniper Rifle'),
  ('ooh-rah','Sniper',              'Fists'),
  ('ooh-rah','Breacher',            'Ooh Rah Shotgun'),
  ('ooh-rah','Breacher',            'Shock Grenades'),
  ('ooh-rah','Breacher',            'Fists'),
  ('ooh-rah','Combat Medic',        'Hi-Vol. Carbine'),
  ('ooh-rah','Combat Medic',        'Hi-Vol. Carbine (Auto)'),
  ('ooh-rah','Combat Medic',        'Fists'),
  ('ooh-rah','Fire Team Leader',    'Hi-Vol. Carbine'),
  ('ooh-rah','Fire Team Leader',    'Hi-Vol. Carbine (Auto)'),
  ('ooh-rah','Fire Team Leader',    'Fists'),
  ('ooh-rah','Rifleman',            'Hi-Vol. Carbine'),
  ('ooh-rah','Rifleman',            'Hi-Vol. Carbine (Auto)'),
  ('ooh-rah','Rifleman',            'Fists'),
  -- raumjager
  ('raumjager','Einsatzkommandant', 'Raumjager Energy Pistol'),
  ('raumjager','Einsatzkommandant', 'Fists'),
  ('raumjager','Flammenjäger',      'Raumjager Flamer'),
  ('raumjager','Flammenjäger',      'Fists'),
  ('raumjager','Totenjäger',        'Auto Rifle'),
  ('raumjager','Totenjäger',        'Fists'),
  ('raumjager','Plasmajäger',       'Plasgun'),
  ('raumjager','Plasmajäger',       'Fists'),
  ('raumjager','Kampfsanitäter',    'Laserkarabiner'),
  ('raumjager','Kampfsanitäter',    'Laserkarabiner (Auto)'),
  ('raumjager','Kampfsanitäter',    'Fists'),
  ('raumjager','Erfahrener Jäger',  'Laserkarabiner'),
  ('raumjager','Erfahrener Jäger',  'Laserkarabiner (Auto)'),
  ('raumjager','Erfahrener Jäger',  'Fists'),
  ('raumjager','Eiserne Jäger',     'Laserkarabiner'),
  ('raumjager','Eiserne Jäger',     'Laserkarabiner (Auto)'),
  ('raumjager','Eiserne Jäger',     'Fists'),
  -- sneakfeet
  ('sneakfeet','Quiet-flinger',  'LRSF Rifle'),
  ('sneakfeet','Quiet-flinger',  'SRSF Rifle'),
  ('sneakfeet','Quiet-flinger',  'Fists'),
  ('sneakfeet','Hardfoot',       'Slug Gun'),
  ('sneakfeet','Hardfoot',       'Fists'),
  ('sneakfeet','Grass-whistler', 'LRSF Rifle'),
  ('sneakfeet','Grass-whistler', 'SRSF Rifle'),
  ('sneakfeet','Grass-whistler', 'Fists'),
  ('sneakfeet','Bombarder',      'Slug Gun'),
  ('sneakfeet','Bombarder',      'SneakFeet Frag Grenade'),
  ('sneakfeet','Bombarder',      'Fists'),
  ('sneakfeet','Pointfoot',      'Slug Gun'),
  ('sneakfeet','Pointfoot',      'Fists'),
  ('sneakfeet','Cook',           'Slug Gun'),
  ('sneakfeet','Cook',           'Frying Pan'),
  ('sneakfeet','Quickfoot',      'Slug Gun'),
  ('sneakfeet','Quickfoot',      'Hunting Knife'),
  ('sneakfeet','Youngfoot',      'Slug Gun'),
  ('sneakfeet','Youngfoot',      'Fists'),
  ('sneakfeet','Stoutfoot',      'Slug Gun'),
  ('sneakfeet','Stoutfoot',      'Fists')
) as v(faction_slug, unit_name, weapon_name)
join ut on ut.name = v.unit_name and ut.faction_slug = v.faction_slug
join w  on w.name  = v.weapon_name
on conflict (unit_type_id, weapon_id) do nothing;
